# Delivery_time -> Predict delivery time using sorting time

In [30]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('H:/Data science/Practice/20 november/2. Simple Linear Regression/delivery_time.csv')
data

Delivery Time  Sorting Time
0           21.00            10
1           13.50             4
2           19.75             6
3           24.00             9
4           29.00            10
5           15.35             6
6           19.00             7
7            9.50             3
8           17.90            10
9           18.75             9
10          19.83             8
11          10.75             4
12          16.68             7
13          11.50             3
14          12.03             3
15          14.88             4
16          13.75             6
17          18.11             7
18           8.00             2
19          17.83             7
20          21.50             5

In [3]:
df = data.copy()

In [4]:
x = df['Sorting Time'].values.reshape(-1,1)
x

array([[10],
       [ 4],
       [ 6],
       [ 9],
       [10],
       [ 6],
       [ 7],
       [ 3],
       [10],
       [ 9],
       [ 8],
       [ 4],
       [ 7],
       [ 3],
       [ 3],
       [ 4],
       [ 6],
       [ 7],
       [ 2],
       [ 7],
       [ 5]], dtype=int64)

In [5]:
y = df['Delivery Time'].values.reshape(-1,1)
y

array([[21.  ],
       [13.5 ],
       [19.75],
       [24.  ],
       [29.  ],
       [15.35],
       [19.  ],
       [ 9.5 ],
       [17.9 ],
       [18.75],
       [19.83],
       [10.75],
       [16.68],
       [11.5 ],
       [12.03],
       [14.88],
       [13.75],
       [18.11],
       [ 8.  ],
       [17.83],
       [21.5 ]])

In [6]:
import sklearn.linear_model as sk

In [7]:
lin = sk.LinearRegression()

In [8]:
w=lin.fit(x,y)
w

LinearRegression()

In [9]:
w.coef_

array([[1.6490199]])

In [10]:
w.intercept_

array([6.58273397])

In [11]:
w.score(x,y)

0.6822714748417231

In [57]:
s1 = float(input('Enter the value of sortintime '))
s2 = float(input('Enter the value of sortintime '))
s3 = float(input('Enter the value of sortintime '))
pred_y1 = (w.coef_*s1) + w.intercept_
pred_y2 = (w.coef_*s2) + w.intercept_
pred_y3 = (w.coef_*s3) + w.intercept_
print('The expeted delivery time is {} for {} sorting time'.format(pred_y1,s1))
print('The expeted delivery time is {} for {} sorting time'.format(pred_y2,s2))
print('The expeted delivery time is {} for {} sorting time'.format(pred_y3,s3))

Enter the value of sortintime 12
Enter the value of sortintime 10
Enter the value of sortintime 5.5
The expeted delivery time is [[26.37097273]] for 12.0 sorting time
The expeted delivery time is [[23.07293294]] for 10.0 sorting time
The expeted delivery time is [[15.6523434]] for 5.5 sorting time


In [15]:
w.predict(x)

array([[23.07293294],
       [13.17881356],
       [16.47685335],
       [21.42391304],
       [23.07293294],
       [16.47685335],
       [18.12587325],
       [11.52979366],
       [23.07293294],
       [21.42391304],
       [19.77489315],
       [13.17881356],
       [18.12587325],
       [11.52979366],
       [11.52979366],
       [13.17881356],
       [16.47685335],
       [18.12587325],
       [ 9.88077377],
       [18.12587325],
       [14.82783346]])

# Salary_hike -> Build a prediction model for Salary_hike 

In [16]:
data2 = pd.read_csv('H:/Data science/Practice/20 november/2. Simple Linear Regression/Salary_Data.csv')
data2

YearsExperience(x)  Salary(y)
0                  1.1      39343
1                  1.3      46205
2                  1.5      37731
3                  2.0      43525
4                  2.2      39891
5                  2.9      56642
6                  3.0      60150
7                  3.2      54445
8                  3.2      64445
9                  3.7      57189
10                 3.9      63218
11                 4.0      55794
12                 4.0      56957
13                 4.1      57081
14                 4.5      61111
15                 4.9      67938
16                 5.1      66029
17                 5.3      83088
18                 5.9      81363
19                 6.0      93940
20                 6.8      91738
21                 7.1      98273
22                 7.9     101302
23                 8.2     113812
24                 8.7     109431
25                 9.0     105582
26                 9.5     116969
27                 9.6     112635
28                10.3     122391
29                10.5     121872

In [17]:
df2=data2.copy()
df2

YearsExperience(x)  Salary(y)
0                  1.1      39343
1                  1.3      46205
2                  1.5      37731
3                  2.0      43525
4                  2.2      39891
5                  2.9      56642
6                  3.0      60150
7                  3.2      54445
8                  3.2      64445
9                  3.7      57189
10                 3.9      63218
11                 4.0      55794
12                 4.0      56957
13                 4.1      57081
14                 4.5      61111
15                 4.9      67938
16                 5.1      66029
17                 5.3      83088
18                 5.9      81363
19                 6.0      93940
20                 6.8      91738
21                 7.1      98273
22                 7.9     101302
23                 8.2     113812
24                 8.7     109431
25                 9.0     105582
26                 9.5     116969
27                 9.6     112635
28                10.3     122391
29                10.5     121872

In [18]:
df2.columns

Index(['YearsExperience(x)', 'Salary(y)'], dtype='object')

In [19]:
x = df2['YearsExperience(x)'].values.reshape(-1,1)
y = df2['Salary(y)'].values.reshape(-1,1)

In [22]:
lin2 = sk.LinearRegression()

In [24]:
v = lin2.fit(x,y)
v

LinearRegression()

In [25]:
v.coef_

array([[9449.96232146]])

In [26]:
v.intercept_

array([25792.20019867])

In [28]:
v.score(x,y)

0.9569566641435086

In [42]:
v.predict(x)

array([[ 36187.15875227],
       [ 38077.15121656],
       [ 39967.14368085],
       [ 44692.12484158],
       [ 46582.11730587],
       [ 53197.09093089],
       [ 54142.08716303],
       [ 56032.07962732],
       [ 56032.07962732],
       [ 60757.06078805],
       [ 62647.05325234],
       [ 63592.04948449],
       [ 63592.04948449],
       [ 64537.04571663],
       [ 68317.03064522],
       [ 72097.0155738 ],
       [ 73987.00803809],
       [ 75877.00050238],
       [ 81546.97789525],
       [ 82491.9741274 ],
       [ 90051.94398456],
       [ 92886.932681  ],
       [100446.90253816],
       [103281.8912346 ],
       [108006.87239533],
       [110841.86109176],
       [115566.84225249],
       [116511.83848464],
       [123126.81210966],
       [125016.80457395]])

In [55]:
v1 = float(input('Enter the value of YearExperience '))
v2 = float(input('Enter the value of YearExperience '))
v3 = float(input('Enter the value of YearExperience '))
h1 =( v.coef_*v1 )+ v.intercept_
h2 =( v.coef_*v2 )+ v.intercept_
h3 =( v.coef_*v3 )+ v.intercept_
print('The expeted salary hike is {} for yearExperience {}'.format(h1,v1))
print('The expeted salary hike is {} for yearExperience {}'.format(h2,v2))
print('The expeted salary hike is {} for yearExperience {}'.format(h3,v3))

Enter the value of YearExperience 1.1
Enter the value of YearExperience 5
Enter the value of YearExperience 5.9
The expeted salary hike is [[36187.15875227]] for yearExperience 1.1
The expeted salary hike is [[73042.01180594]] for yearExperience 5.0
The expeted salary hike is [[81546.97789525]] for yearExperience 5.9
